import axios from 'axios'
const api = axios.create({ baseURL: '/api/v1' })
api.interceptors.request.use(c => { const t = localStorage.getItem('token'); if(t) c.headers.Authorization = 'Bearer '+t; return c })
export const authAPI = { login: d => api.post('/auth/login',d), loginCode: d => api.post('/auth/login-code',d), register: d => api.post('/auth/register',d), sendCode: d => api.post('/auth/send-code',d), changePassword: d => api.post('/auth/change-password',d) }
export const usersAPI = { me: () => api.get('/users/me'), publicProfile: id => api.get('/users/'+id+'/public'), userStats: id => api.get('/users/'+id+'/stats'), achievements: () => api.get('/users/me/achievements'), friends: () => api.get('/users/friends'), messages: () => api.get('/users/messages'), pendingFriendRequests: () => api.get('/users/friend-requests/pending'), removeFriend: id => api.delete('/users/friends/'+id), updateProfile: d => api.put('/users/me',d), updateMe: d => api.put('/users/me',d), sendMessage: d => api.post('/users/messages', d), messagesWith: uid => api.get('/users/messages/with/'+uid) }
export const activitiesAPI = { list: p => api.get('/activities',{params:p}), create: d => api.post('/activities',d), nearby: p => api.get('/activities/nearby',{params:p}), categories: () => api.get('/activities/categories'), tags: () => api.get('/activities/tags'), my: p => api.get('/activities/my',{params:p}), myFavorites: () => api.get('/activities/my-favorites'), detail: id => api.get('/activities/'+id), signups: id => api.get('/activities/'+id+'/signups'), signup: id => api.post('/activities/'+id+'/signup'), cancelSignup: id => api.post('/activities/'+id+'/cancel'), cancel: id => api.delete('/activities/'+id+'/signup'), checkin: id => api.post('/activities/'+id+'/checkin'), favor: id => api.post('/activities/'+id+'/favorite'), favorite: id => api.post('/activities/'+id+'/favorite'), unfavorite: id => api.delete('/activities/'+id+'/favorite'), complete: id => api.post('/activities/'+id+'/complete'), disband: id => api.post('/activities/'+id+'/disband'), update: (id, d) => api.put('/activities/'+id, d), weather: id => api.get('/activities/'+id+'/weather'), albums: id => api.get('/activities/'+id+'/albums') }
export const chatAPI = { groups: () => api.get('/chat/groups'), messages: gid => api.get('/chat/groups/'+gid+'/messages'), sendMessage: (gid, d) => api.post('/chat/groups/'+gid+'/messages', d), readMessages: gid => api.post('/chat/groups/'+gid+'/read'), groupDetail: gid => api.get('/chat/groups/'+gid+'/detail'), leaveGroup: gid => api.delete('/chat/groups/'+gid+'/leave') }
export const uploadAPI = { avatar: d => api.post('/users/upload-avatar', d, { headers: { 'Content-Type': 'multipart/form-data' } }) }
export default api
